---
title           : "My preregistration example for PREE"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Andres Mancera Barreto
    affiliation : 1


affiliation:
  - id          : 1
    institution : University of British Columbia


output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**No**, no data have been collected for this study yet.

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> There is no hypothesis to be tested, as this is an excersice.

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> My grades

## Conditions

<!-- How many and which conditions will participants be assigned to? -->

> How well written this project is

## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> No analyses will be necessary besides understanding what has probably gone wrong after receiving a grade.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> Example 1: We will compute the overall mean and standard deviation across all conditions, and winsorize at 2.5 SD above/below the mean. Example 2: We will exclude participants who incorrectly answer at least 2 of our 3 attention check questions. Example 3: We will exclude any participants who complete the survey in less than 30 seconds.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> It will be of 1

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

> Not in reality. Again, this is an excersice.

## Study type

Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

-   Class project or assignment

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
