---
title: "PREE_Assignment"
author: "Andres Mancera Barreto"
date: "2023-09-19"
output: pdf_document
bibliography: ["references.bib", "grateful-refs.bib"]
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/ecological-entomology.csl"
---

```{r, include=FALSE}
library(tidyverse)
library(palmerpenguins)
library(grateful)
```


## Title

### Abstract

### Introduction

There are several efforts to study biodiversity and the effects of climate change in both patch and diversity indexes [@cahill2013; @carey2003; @harvey2023].

### Methods

### Results


|island    | Adelie| Chinstrap| Gentoo| Total|
|:---------|------:|---------:|------:|-----:|
|Biscoe    |     44|         0|    124|   168|
|Dream     |     56|        68|      0|   124|
|Torgersen |     52|         0|      0|    52|
|Total     |    152|        68|    124|   344|


### Discussion

### Tables

### Figure captions

### Figures



### Appendices

### References

```{r, include=FALSE}
cite_packages(output = "paragraph", out.dir = getwd())
```