---
title           : "My preregistration example for PREE"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Andres Mancera Barreto
    affiliation : 1


affiliation:
  - id          : 1
    institution : University of British Columbia


output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

This study is using available data from the "palmerpenguins" package in R, that
contains the information of different penguin populations that were sureveyed.
Some data has been collected but not by me.

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> There is an association between the penguin species abundance and the the island surveyed.

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> The penguin species abundance (and my grades)

## Conditions

<!-- How many and which conditions will participants be assigned to? -->

> The island where data was collected (and how well this is written)

## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> A chi squared contingency test will be done between the islands and spp. to 
test for variations in the number of penguins that belong to a species.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> eeeeh, yes?

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> The information has already been collected. There are just 344 observations

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

> Not in reality. Again, this is an excersice.

## Study type

Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

-   Class project or assignment

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
